# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('TL', 'TL'), ('PM', 'PM'), ('Dev', 'Dev')], default='Dev', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='dev_in_projects', to='team.Person')),
                ('project_manager', models.ManyToManyField(blank=True, related_name='pm_in_projects', to='team.Person')),
                ('team_lead', models.ManyToManyField(blank=True, related_name='tl_in_projects', to='team.Person')),
            ],
        ),
    ]
