# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='people_with_skill', to='team.Skill'),
        ),
    ]
