# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160620_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='developers',
            new_name='skills',
        ),
    ]
